### ISSUE TITLE
`Flat` missing `u_NormalRotation`

### ISSUE THREAD

**Issue by ghost** [kvark/gfx_pipeline#9]
The [params ](https://github.com/kvark/gfx_pipeline/blob/master/src/flat/mod.rs#L17) are missing `u_NormalRotation`. Which is needed by the [phong shader](https://github.com/kvark/gfx_pipeline/blob/master/gpu/phong.glslv#L4).

**Comment by kvark** [comment]
I don't think `Flat` needs the normal at all, it's not supposed to do any lighting. Perhaps, we should just clean up the flat shader instead of providing `u_NormalRotation`.
